### PR TITLE
Build Migrations and Models for DB Structure

### PR DESCRIPTION
**Pull request by alanunruh**
Model, Migrations, and Associations for the following models:

- Game

- Piece

- Move

*User model was previously created during the devise install

### CODE REVIEW

**Comment by bountonw** [comment]
There is a game_status_id but no game_status table.
There are no foreign keys to connect the three models. How do you associate moves, pieces and games?

**Review by bountonw — CHANGES_REQUESTED** [review]
There is a game_status_id but no game_status table.
There are no foreign keys to connect the three models. How do you associate moves, pieces and games?

**Comment by alanunruh** [comment]
I have the models set up with the 'belongs_to' and 'has_many' associations. Do we need foreign keys as well?

**Comment by alanunruh** [comment]
In regards to the game_status_id I was under the impression via slack that you wanted it rolled up under the game model.

**Review by bountonw — DISMISSED** [review]

**Comment by bountonw** [comment]
I think as we go to the building out of our logic next week, the questions that I raised will resolve themselves one way or another. I'm approving now so that we can move forward.

**Review by jiro-sains — COMMENTED** [review]
so, my main comment is that moves_taken in table moves was supposed to be an array that would contain all the moves of that particular game. Maybe the logic is flawed. But I wonder would this work with and integer?

**Comment by bountonw** [comment]
Good catch, Yes. moves_taken has to be an array. Glad you caught that.

**Review by alysonpaige — DISMISSED** [review]
For what it's worth from my corner, this looks great - thank you for taking care of this in my absence.

**Comment by alanunruh** [comment]
I've updated this branch with the requested changes to the moves table:
`t.string :moves_taken, array: true, default: []`

**Comment by alanunruh** [comment]
Commit `edit test and rspec files` resolves the test/rspec file issues.

**Review by bountonw — APPROVED** [review]
Good work Alan. I still have some questions, but they will be answered in the next phase.

**Review by alysonpaige — APPROVED** [review]
I'll have some follow-up questions on some of these changes once I'm grounded in front of a computer again but it looks good - thanks again, Alan.

**Pull request merged**
